Hosts = x
PayloadSize = 100
CellSizeDown = 100
RelayWindowSize = 5
DCNetType = "Simple"
RelayReportingLimit = -1
RelayMaxNumberOfConsecutiveFailedRounds = 5
RelayProcessingLoopSleepTime = 0
RelayRoundTimeOut = 20000
RelayTrusteeCacheLowBound = 10000
RelayTrusteeCacheHighBound = 50000
RelayUseDummyDataDown = false
RelayDataOutputEnabled = false
ClientDataOutputEnabled = false
UseUDP = true
DoLatencyTests = true
ReplayPCAP = false
PCAPFolder = "pcap/"
DisruptionProtectionEnabled = false
RelayUseOpenClosedSlots = true
OpenClosedSlotsMinDelayBetweenRequests = 0
TrusteeSleepTimeBetweenMessages = 10
TrusteeAlwaysSlowDown = false
TrusteeNeverSlowDown = false
SocksServerPort = 8080
SocksClientPort = 8090
TrusteeIPRegexPattern = "10\\.1\\.0\\.([0-9]+)"
ClientIPRegexPattern = "10\\.0\\.1\\.([0-9]+)"
RelayIPRegexPattern = "10\\.([0-9]+)\\.([0-9]+)\\.254"
OverrideLogLevel = 1
ForceConsoleColor = true
Simulation = "PriFi"
Servers = 9
Depth = 1
CloseWait = "10000000ms"
RunWait = "10000000ms"
NTrustees = 3
SimulDelayBetweenClients = 0
Suite = "Ed25519"
SchedulerStrategy = "Latency"

Rounds
1
