Hosts = x
PayloadSize = 100
CellSizeDown = 100
RelayWindowSize = 2
DCNetType = "Simple"
RelayReportingLimit = 100000
RelayMaxNumberOfConsecutiveFailedRounds = 3
RelayProcessingLoopSleepTime = 0
RelayRoundTimeOut = 1000
RelayTrusteeCacheLowBound = 10000
RelayTrusteeCacheHighBound = 15000
RelayUseDummyDataDown = false
RelayDataOutputEnabled = false
ClientDataOutputEnabled = false
UseUDP = true
DoLatencyTests = true
ReplayPCAP = false
PCAPFolder = "pcap/"
DisruptionProtectionEnabled = false
RelayUseOpenClosedSlots = true
OpenClosedSlotsMinDelayBetweenRequests = 10
TrusteeSleepTimeBetweenMessages = 1000
TrusteeAlwaysSlowDown = false
TrusteeNeverSlowDown = false
EquivocationProtectionEnabled = false
SocksServerPort = 8080
SocksClientPort = 8090
TrusteeIPRegexPattern = "(10\\.1\\.0\\.([0-9]+))|(10\\.2\\.0\\.250)"
ClientIPRegexPattern = "10\\.0\\.1\\.([0-9]+)"
RelayIPRegexPattern = "10\\.([0-9]+)\\.([0-9]+)\\.254"
OverrideLogLevel = 1
ForceConsoleColor = true
Simulation = "PriFi"
Servers = 9
Depth = 1
CloseWait = "10000000ms"
RunWait = "10000000ms"
NTrustees = 3
SimulDelayBetweenClients = 0
Suite = "Ed25519"

Rounds
1
