Login = "lbarman"
Host = "users.deterlab.net"
Project = "SAFER"
Experiment = "LB-LLD"
ProxyAddress = "localhost"
MonitorAddress = "users.isi.deterlab.net"
MonitorPort = 10002
Servers = 9
Simulation = "PriFi"
Hosts = 94
Debug = 0
RunWait = 10000000
PreScript = ""
